import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from '@/components/Providers';
import Header from '@/components/layouts/Header';
import Footer from '@/components/layouts/Footer';
import Nav from '@/components/layouts/Nav/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <Providers>
          <Header>Top header</Header>
          <Nav />
          {children}
          <Footer>Footer</Footer>
        </Providers>
      </body>
    </html>
  );
}
